# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DVP.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1002, 586)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_10 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pushButton_saveparameter = QtGui.QPushButton(self.tab)
        self.pushButton_saveparameter.setObjectName(_fromUtf8("pushButton_saveparameter"))
        self.gridLayout_6.addWidget(self.pushButton_saveparameter, 3, 2, 1, 1)
        self.pushButton_denyparameter = QtGui.QPushButton(self.tab)
        self.pushButton_denyparameter.setObjectName(_fromUtf8("pushButton_denyparameter"))
        self.gridLayout_6.addWidget(self.pushButton_denyparameter, 3, 1, 1, 1)
        self.groupBox_BPAprogram = QtGui.QGroupBox(self.tab)
        self.groupBox_BPAprogram.setObjectName(_fromUtf8("groupBox_BPAprogram"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_BPAprogram)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.toolButton_swntprogram = QtGui.QToolButton(self.groupBox_BPAprogram)
        self.toolButton_swntprogram.setObjectName(_fromUtf8("toolButton_swntprogram"))
        self.gridLayout_4.addWidget(self.toolButton_swntprogram, 0, 2, 1, 1)
        self.lineEdit_swntprogram = QtGui.QLineEdit(self.groupBox_BPAprogram)
        self.lineEdit_swntprogram.setObjectName(_fromUtf8("lineEdit_swntprogram"))
        self.gridLayout_4.addWidget(self.lineEdit_swntprogram, 0, 1, 1, 1)
        self.label_pfprogram = QtGui.QLabel(self.groupBox_BPAprogram)
        self.label_pfprogram.setObjectName(_fromUtf8("label_pfprogram"))
        self.gridLayout_4.addWidget(self.label_pfprogram, 1, 0, 1, 1)
        self.label_resultfile = QtGui.QLabel(self.groupBox_BPAprogram)
        self.label_resultfile.setObjectName(_fromUtf8("label_resultfile"))
        self.gridLayout_4.addWidget(self.label_resultfile, 2, 0, 1, 1)
        self.toolButton_resultfile = QtGui.QToolButton(self.groupBox_BPAprogram)
        self.toolButton_resultfile.setObjectName(_fromUtf8("toolButton_resultfile"))
        self.gridLayout_4.addWidget(self.toolButton_resultfile, 2, 2, 1, 1)
        self.lineEdit_resultfile = QtGui.QLineEdit(self.groupBox_BPAprogram)
        self.lineEdit_resultfile.setObjectName(_fromUtf8("lineEdit_resultfile"))
        self.gridLayout_4.addWidget(self.lineEdit_resultfile, 2, 1, 1, 1)
        self.label_swntprogram = QtGui.QLabel(self.groupBox_BPAprogram)
        self.label_swntprogram.setObjectName(_fromUtf8("label_swntprogram"))
        self.gridLayout_4.addWidget(self.label_swntprogram, 0, 0, 1, 1)
        self.lineEdit_pfprogram = QtGui.QLineEdit(self.groupBox_BPAprogram)
        self.lineEdit_pfprogram.setObjectName(_fromUtf8("lineEdit_pfprogram"))
        self.gridLayout_4.addWidget(self.lineEdit_pfprogram, 1, 1, 1, 1)
        self.toolButton_pfprogram = QtGui.QToolButton(self.groupBox_BPAprogram)
        self.toolButton_pfprogram.setObjectName(_fromUtf8("toolButton_pfprogram"))
        self.gridLayout_4.addWidget(self.toolButton_pfprogram, 1, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_BPAprogram, 1, 0, 1, 3)
        self.groupBox_systemparameter = QtGui.QGroupBox(self.tab)
        self.groupBox_systemparameter.setObjectName(_fromUtf8("groupBox_systemparameter"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_systemparameter)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_loadrate = QtGui.QLabel(self.groupBox_systemparameter)
        self.label_loadrate.setObjectName(_fromUtf8("label_loadrate"))
        self.gridLayout_3.addWidget(self.label_loadrate, 0, 0, 1, 1)
        self.doubleSpinBox_loadrate = QtGui.QDoubleSpinBox(self.groupBox_systemparameter)
        self.doubleSpinBox_loadrate.setDecimals(2)
        self.doubleSpinBox_loadrate.setMaximum(1.0)
        self.doubleSpinBox_loadrate.setSingleStep(0.01)
        self.doubleSpinBox_loadrate.setProperty("value", 0.0)
        self.doubleSpinBox_loadrate.setObjectName(_fromUtf8("doubleSpinBox_loadrate"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_loadrate, 0, 1, 1, 1)
        self.label_dlrate = QtGui.QLabel(self.groupBox_systemparameter)
        self.label_dlrate.setObjectName(_fromUtf8("label_dlrate"))
        self.gridLayout_3.addWidget(self.label_dlrate, 1, 0, 1, 1)
        self.doubleSpinBox_dlrate = QtGui.QDoubleSpinBox(self.groupBox_systemparameter)
        self.doubleSpinBox_dlrate.setDecimals(2)
        self.doubleSpinBox_dlrate.setMaximum(1.0)
        self.doubleSpinBox_dlrate.setSingleStep(0.01)
        self.doubleSpinBox_dlrate.setProperty("value", 0.5)
        self.doubleSpinBox_dlrate.setObjectName(_fromUtf8("doubleSpinBox_dlrate"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_dlrate, 1, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_systemparameter, 2, 1, 1, 2)
        self.groupBox_systemdata = QtGui.QGroupBox(self.tab)
        self.groupBox_systemdata.setObjectName(_fromUtf8("groupBox_systemdata"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_systemdata)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_pfdata = QtGui.QLabel(self.groupBox_systemdata)
        self.label_pfdata.setObjectName(_fromUtf8("label_pfdata"))
        self.gridLayout_2.addWidget(self.label_pfdata, 0, 0, 1, 1)
        self.lineEdit_pfdata = QtGui.QLineEdit(self.groupBox_systemdata)
        self.lineEdit_pfdata.setObjectName(_fromUtf8("lineEdit_pfdata"))
        self.gridLayout_2.addWidget(self.lineEdit_pfdata, 0, 1, 1, 1)
        self.toolButton_pfdata = QtGui.QToolButton(self.groupBox_systemdata)
        self.toolButton_pfdata.setObjectName(_fromUtf8("toolButton_pfdata"))
        self.gridLayout_2.addWidget(self.toolButton_pfdata, 0, 2, 1, 1)
        self.label_bsedata = QtGui.QLabel(self.groupBox_systemdata)
        self.label_bsedata.setObjectName(_fromUtf8("label_bsedata"))
        self.gridLayout_2.addWidget(self.label_bsedata, 1, 0, 1, 1)
        self.lineEdit_bsedata = QtGui.QLineEdit(self.groupBox_systemdata)
        self.lineEdit_bsedata.setObjectName(_fromUtf8("lineEdit_bsedata"))
        self.gridLayout_2.addWidget(self.lineEdit_bsedata, 1, 1, 1, 1)
        self.toolButton__bsedata = QtGui.QToolButton(self.groupBox_systemdata)
        self.toolButton__bsedata.setObjectName(_fromUtf8("toolButton__bsedata"))
        self.gridLayout_2.addWidget(self.toolButton__bsedata, 1, 2, 1, 1)
        self.label_changedata = QtGui.QLabel(self.groupBox_systemdata)
        self.label_changedata.setObjectName(_fromUtf8("label_changedata"))
        self.gridLayout_2.addWidget(self.label_changedata, 2, 0, 1, 1)
        self.lineEdit_changedata = QtGui.QLineEdit(self.groupBox_systemdata)
        self.lineEdit_changedata.setObjectName(_fromUtf8("lineEdit_changedata"))
        self.gridLayout_2.addWidget(self.lineEdit_changedata, 2, 1, 1, 1)
        self.toolButton_changedata = QtGui.QToolButton(self.groupBox_systemdata)
        self.toolButton_changedata.setObjectName(_fromUtf8("toolButton_changedata"))
        self.gridLayout_2.addWidget(self.toolButton_changedata, 2, 2, 1, 1)
        self.label_swntdata = QtGui.QLabel(self.groupBox_systemdata)
        self.label_swntdata.setObjectName(_fromUtf8("label_swntdata"))
        self.gridLayout_2.addWidget(self.label_swntdata, 3, 0, 1, 1)
        self.lineEdit_swntdata = QtGui.QLineEdit(self.groupBox_systemdata)
        self.lineEdit_swntdata.setObjectName(_fromUtf8("lineEdit_swntdata"))
        self.gridLayout_2.addWidget(self.lineEdit_swntdata, 3, 1, 1, 1)
        self.toolButton_swntdata = QtGui.QToolButton(self.groupBox_systemdata)
        self.toolButton_swntdata.setObjectName(_fromUtf8("toolButton_swntdata"))
        self.gridLayout_2.addWidget(self.toolButton_swntdata, 3, 2, 1, 1)
        self.label_falutratedata = QtGui.QLabel(self.groupBox_systemdata)
        self.label_falutratedata.setObjectName(_fromUtf8("label_falutratedata"))
        self.gridLayout_2.addWidget(self.label_falutratedata, 4, 0, 1, 1)
        self.lineEdit_faultratedata = QtGui.QLineEdit(self.groupBox_systemdata)
        self.lineEdit_faultratedata.setObjectName(_fromUtf8("lineEdit_faultratedata"))
        self.gridLayout_2.addWidget(self.lineEdit_faultratedata, 4, 1, 1, 1)
        self.toolButton_faultratedata = QtGui.QToolButton(self.groupBox_systemdata)
        self.toolButton_faultratedata.setObjectName(_fromUtf8("toolButton_faultratedata"))
        self.gridLayout_2.addWidget(self.toolButton_faultratedata, 4, 2, 1, 1)
        self.label_mapdata = QtGui.QLabel(self.groupBox_systemdata)
        self.label_mapdata.setObjectName(_fromUtf8("label_mapdata"))
        self.gridLayout_2.addWidget(self.label_mapdata, 5, 0, 1, 1)
        self.lineEdit_mapdata = QtGui.QLineEdit(self.groupBox_systemdata)
        self.lineEdit_mapdata.setObjectName(_fromUtf8("lineEdit_mapdata"))
        self.gridLayout_2.addWidget(self.lineEdit_mapdata, 5, 1, 1, 1)
        self.toolButton_mapdata = QtGui.QToolButton(self.groupBox_systemdata)
        self.toolButton_mapdata.setObjectName(_fromUtf8("toolButton_mapdata"))
        self.gridLayout_2.addWidget(self.toolButton_mapdata, 5, 2, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_systemdata, 0, 0, 1, 3)
        self.groupBox_DVparameter = QtGui.QGroupBox(self.tab)
        self.groupBox_DVparameter.setObjectName(_fromUtf8("groupBox_DVparameter"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_DVparameter)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_dvtype = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_dvtype.setObjectName(_fromUtf8("label_dvtype"))
        self.gridLayout.addWidget(self.label_dvtype, 0, 0, 1, 1)
        self.label_maxrate = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_maxrate.setObjectName(_fromUtf8("label_maxrate"))
        self.gridLayout.addWidget(self.label_maxrate, 0, 1, 1, 1)
        self.label_mingap = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_mingap.setObjectName(_fromUtf8("label_mingap"))
        self.gridLayout.addWidget(self.label_mingap, 0, 3, 1, 1)
        self.label_fixedcost = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_fixedcost.setObjectName(_fromUtf8("label_fixedcost"))
        self.gridLayout.addWidget(self.label_fixedcost, 0, 5, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 0, 7, 1, 1)
        self.checkBox_statcom = QtGui.QCheckBox(self.groupBox_DVparameter)
        self.checkBox_statcom.setObjectName(_fromUtf8("checkBox_statcom"))
        self.gridLayout.addWidget(self.checkBox_statcom, 1, 0, 1, 1)
        self.lineEdit__cc = QtGui.QLineEdit(self.groupBox_DVparameter)
        self.lineEdit__cc.setObjectName(_fromUtf8("lineEdit__cc"))
        self.gridLayout.addWidget(self.lineEdit__cc, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 1, 2, 1, 1)
        self.lineEdit_mingapstatcom = QtGui.QLineEdit(self.groupBox_DVparameter)
        self.lineEdit_mingapstatcom.setObjectName(_fromUtf8("lineEdit_mingapstatcom"))
        self.gridLayout.addWidget(self.lineEdit_mingapstatcom, 1, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 1, 4, 1, 1)
        self.lineEdit_fixedcostatcom = QtGui.QLineEdit(self.groupBox_DVparameter)
        self.lineEdit_fixedcostatcom.setObjectName(_fromUtf8("lineEdit_fixedcostatcom"))
        self.gridLayout.addWidget(self.lineEdit_fixedcostatcom, 1, 5, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout.addWidget(self.label_35, 1, 6, 1, 1)
        self.lineEdit_pcoststatcom = QtGui.QLineEdit(self.groupBox_DVparameter)
        self.lineEdit_pcoststatcom.setObjectName(_fromUtf8("lineEdit_pcoststatcom"))
        self.gridLayout.addWidget(self.lineEdit_pcoststatcom, 1, 7, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 1, 8, 1, 1)
        self.checkBox_svc = QtGui.QCheckBox(self.groupBox_DVparameter)
        self.checkBox_svc.setObjectName(_fromUtf8("checkBox_svc"))
        self.gridLayout.addWidget(self.checkBox_svc, 2, 0, 1, 1)
        self.lineEdit_maxratesvc = QtGui.QLineEdit(self.groupBox_DVparameter)
        self.lineEdit_maxratesvc.setObjectName(_fromUtf8("lineEdit_maxratesvc"))
        self.gridLayout.addWidget(self.lineEdit_maxratesvc, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 2, 2, 1, 1)
        self.lineEdit_mingapsvc = QtGui.QLineEdit(self.groupBox_DVparameter)
        self.lineEdit_mingapsvc.setObjectName(_fromUtf8("lineEdit_mingapsvc"))
        self.gridLayout.addWidget(self.lineEdit_mingapsvc, 2, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 2, 4, 1, 1)
        self.lineEdit_fixedcostsvc = QtGui.QLineEdit(self.groupBox_DVparameter)
        self.lineEdit_fixedcostsvc.setObjectName(_fromUtf8("lineEdit_fixedcostsvc"))
        self.gridLayout.addWidget(self.lineEdit_fixedcostsvc, 2, 5, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout.addWidget(self.label_36, 2, 6, 1, 1)
        self.lineEdit_pcostsvc = QtGui.QLineEdit(self.groupBox_DVparameter)
        self.lineEdit_pcostsvc.setObjectName(_fromUtf8("lineEdit_pcostsvc"))
        self.gridLayout.addWidget(self.lineEdit_pcostsvc, 2, 7, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_DVparameter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout.addWidget(self.label_38, 2, 8, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_DVparameter, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.pushButton_faultanalyse = QtGui.QPushButton(self.tab_2)
        self.pushButton_faultanalyse.setObjectName(_fromUtf8("pushButton_faultanalyse"))
        self.gridLayout_12.addWidget(self.pushButton_faultanalyse, 0, 0, 1, 1)
        self.groupBox_chooseignorefault = QtGui.QGroupBox(self.tab_2)
        self.groupBox_chooseignorefault.setObjectName(_fromUtf8("groupBox_chooseignorefault"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_chooseignorefault)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.comboBox_choosefault = QtGui.QComboBox(self.groupBox_chooseignorefault)
        self.comboBox_choosefault.setEditable(True)
        self.comboBox_choosefault.setDuplicatesEnabled(False)
        self.comboBox_choosefault.setObjectName(_fromUtf8("comboBox_choosefault"))
        self.gridLayout_15.addWidget(self.comboBox_choosefault, 0, 0, 1, 1)
        self.pushButton_addfault = QtGui.QPushButton(self.groupBox_chooseignorefault)
        self.pushButton_addfault.setObjectName(_fromUtf8("pushButton_addfault"))
        self.gridLayout_15.addWidget(self.pushButton_addfault, 0, 1, 1, 1)
        self.pushButton_canclefault = QtGui.QPushButton(self.groupBox_chooseignorefault)
        self.pushButton_canclefault.setObjectName(_fromUtf8("pushButton_canclefault"))
        self.gridLayout_15.addWidget(self.pushButton_canclefault, 0, 2, 1, 1)
        self.listWidget_ignorefault = QtGui.QListWidget(self.groupBox_chooseignorefault)
        self.listWidget_ignorefault.setObjectName(_fromUtf8("listWidget_ignorefault"))
        self.gridLayout_15.addWidget(self.listWidget_ignorefault, 1, 0, 1, 3)
        self.gridLayout_12.addWidget(self.groupBox_chooseignorefault, 0, 1, 3, 1)
        self.groupBox_mapkeyfault = QtGui.QGroupBox(self.tab_2)
        self.groupBox_mapkeyfault.setObjectName(_fromUtf8("groupBox_mapkeyfault"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_mapkeyfault)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.matplotlibwidget_mapkeyfault = MatplotlibWidget(self.groupBox_mapkeyfault)
        self.matplotlibwidget_mapkeyfault.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibwidget_mapkeyfault.sizePolicy().hasHeightForWidth())
        self.matplotlibwidget_mapkeyfault.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.matplotlibwidget_mapkeyfault.setFont(font)
        self.matplotlibwidget_mapkeyfault.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.matplotlibwidget_mapkeyfault.setStyleSheet(_fromUtf8("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.339795 rgba(255, 0, 0, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));"))
        self.matplotlibwidget_mapkeyfault.setObjectName(_fromUtf8("matplotlibwidget_mapkeyfault"))
        self.gridLayout_11.addWidget(self.matplotlibwidget_mapkeyfault, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_mapkeyfault, 0, 2, 4, 1)
        self.pushButton_kmeansfault = QtGui.QPushButton(self.tab_2)
        self.pushButton_kmeansfault.setObjectName(_fromUtf8("pushButton_kmeansfault"))
        self.gridLayout_12.addWidget(self.pushButton_kmeansfault, 1, 0, 1, 1)
        self.pushButton_mapkeyfault = QtGui.QPushButton(self.tab_2)
        self.pushButton_mapkeyfault.setObjectName(_fromUtf8("pushButton_mapkeyfault"))
        self.gridLayout_12.addWidget(self.pushButton_mapkeyfault, 2, 0, 1, 1)
        self.groupBox_barkeyfault = QtGui.QGroupBox(self.tab_2)
        self.groupBox_barkeyfault.setObjectName(_fromUtf8("groupBox_barkeyfault"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_barkeyfault)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.matplotlibwidget_barkeyfault = MatplotlibWidget(self.groupBox_barkeyfault)
        self.matplotlibwidget_barkeyfault.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibwidget_barkeyfault.sizePolicy().hasHeightForWidth())
        self.matplotlibwidget_barkeyfault.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.matplotlibwidget_barkeyfault.setFont(font)
        self.matplotlibwidget_barkeyfault.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.matplotlibwidget_barkeyfault.setStyleSheet(_fromUtf8("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.339795 rgba(255, 0, 0, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));"))
        self.matplotlibwidget_barkeyfault.setObjectName(_fromUtf8("matplotlibwidget_barkeyfault"))
        self.gridLayout_7.addWidget(self.matplotlibwidget_barkeyfault, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_barkeyfault, 3, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_13 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.pushButton_senscompute = QtGui.QPushButton(self.tab_3)
        self.pushButton_senscompute.setObjectName(_fromUtf8("pushButton_senscompute"))
        self.gridLayout_13.addWidget(self.pushButton_senscompute, 0, 0, 1, 1)
        self.pushButton_senskmeans = QtGui.QPushButton(self.tab_3)
        self.pushButton_senskmeans.setObjectName(_fromUtf8("pushButton_senskmeans"))
        self.gridLayout_13.addWidget(self.pushButton_senskmeans, 1, 0, 1, 1)
        self.pushButton_mapsens = QtGui.QPushButton(self.tab_3)
        self.pushButton_mapsens.setObjectName(_fromUtf8("pushButton_mapsens"))
        self.gridLayout_13.addWidget(self.pushButton_mapsens, 2, 0, 1, 1)
        self.groupBox_ignorebus = QtGui.QGroupBox(self.tab_3)
        self.groupBox_ignorebus.setObjectName(_fromUtf8("groupBox_ignorebus"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_ignorebus)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.pushButton_addbus = QtGui.QPushButton(self.groupBox_ignorebus)
        self.pushButton_addbus.setObjectName(_fromUtf8("pushButton_addbus"))
        self.gridLayout_16.addWidget(self.pushButton_addbus, 0, 1, 1, 1)
        self.pushButton_canclebus = QtGui.QPushButton(self.groupBox_ignorebus)
        self.pushButton_canclebus.setObjectName(_fromUtf8("pushButton_canclebus"))
        self.gridLayout_16.addWidget(self.pushButton_canclebus, 0, 2, 1, 1)
        self.comboBox_choosebus = QtGui.QComboBox(self.groupBox_ignorebus)
        self.comboBox_choosebus.setEditable(True)
        self.comboBox_choosebus.setDuplicatesEnabled(False)
        self.comboBox_choosebus.setObjectName(_fromUtf8("comboBox_choosebus"))
        self.gridLayout_16.addWidget(self.comboBox_choosebus, 0, 0, 1, 1)
        self.listWidget_ignorebus = QtGui.QListWidget(self.groupBox_ignorebus)
        self.listWidget_ignorebus.setObjectName(_fromUtf8("listWidget_ignorebus"))
        self.gridLayout_16.addWidget(self.listWidget_ignorebus, 1, 0, 1, 3)
        self.gridLayout_13.addWidget(self.groupBox_ignorebus, 0, 1, 3, 1)
        self.groupBox_mapsens = QtGui.QGroupBox(self.tab_3)
        self.groupBox_mapsens.setObjectName(_fromUtf8("groupBox_mapsens"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_mapsens)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.matplotlibwidget_mapsens = MatplotlibWidget(self.groupBox_mapsens)
        self.matplotlibwidget_mapsens.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibwidget_mapsens.sizePolicy().hasHeightForWidth())
        self.matplotlibwidget_mapsens.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.matplotlibwidget_mapsens.setFont(font)
        self.matplotlibwidget_mapsens.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.matplotlibwidget_mapsens.setStyleSheet(_fromUtf8("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.339795 rgba(255, 0, 0, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));"))
        self.matplotlibwidget_mapsens.setObjectName(_fromUtf8("matplotlibwidget_mapsens"))
        self.gridLayout_8.addWidget(self.matplotlibwidget_mapsens, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_mapsens, 0, 2, 4, 1)
        self.groupBox_sensbus = QtGui.QGroupBox(self.tab_3)
        self.groupBox_sensbus.setObjectName(_fromUtf8("groupBox_sensbus"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_sensbus)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.matplotlibwidget_barbus = MatplotlibWidget(self.groupBox_sensbus)
        self.matplotlibwidget_barbus.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibwidget_barbus.sizePolicy().hasHeightForWidth())
        self.matplotlibwidget_barbus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.matplotlibwidget_barbus.setFont(font)
        self.matplotlibwidget_barbus.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.matplotlibwidget_barbus.setStyleSheet(_fromUtf8("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.339795 rgba(255, 0, 0, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));"))
        self.matplotlibwidget_barbus.setObjectName(_fromUtf8("matplotlibwidget_barbus"))
        self.gridLayout_9.addWidget(self.matplotlibwidget_barbus, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_sensbus, 3, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.groupBox_optimparameter = QtGui.QGroupBox(self.tab_4)
        self.groupBox_optimparameter.setObjectName(_fromUtf8("groupBox_optimparameter"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_optimparameter)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_typealgorithm = QtGui.QLabel(self.groupBox_optimparameter)
        self.label_typealgorithm.setObjectName(_fromUtf8("label_typealgorithm"))
        self.gridLayout_5.addWidget(self.label_typealgorithm, 0, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_optimparameter)
        self.comboBox_2.setFrame(True)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_5.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_optimparameter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_5.addWidget(self.label_33, 0, 2, 1, 1)
        self.spinBox_randomseed = QtGui.QSpinBox(self.groupBox_optimparameter)
        self.spinBox_randomseed.setMaximum(100)
        self.spinBox_randomseed.setProperty("value", 0)
        self.spinBox_randomseed.setObjectName(_fromUtf8("spinBox_randomseed"))
        self.gridLayout_5.addWidget(self.spinBox_randomseed, 0, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_optimparameter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_5.addWidget(self.label_27, 0, 4, 1, 1)
        self.spinBox_popsize = QtGui.QSpinBox(self.groupBox_optimparameter)
        self.spinBox_popsize.setMaximum(300)
        self.spinBox_popsize.setProperty("value", 50)
        self.spinBox_popsize.setObjectName(_fromUtf8("spinBox_popsize"))
        self.gridLayout_5.addWidget(self.spinBox_popsize, 0, 5, 1, 1)
        self.label_maxinterate = QtGui.QLabel(self.groupBox_optimparameter)
        self.label_maxinterate.setObjectName(_fromUtf8("label_maxinterate"))
        self.gridLayout_5.addWidget(self.label_maxinterate, 1, 0, 1, 1)
        self.spinBox_maxinterate = QtGui.QSpinBox(self.groupBox_optimparameter)
        self.spinBox_maxinterate.setMaximum(1000)
        self.spinBox_maxinterate.setProperty("value", 100)
        self.spinBox_maxinterate.setObjectName(_fromUtf8("spinBox_maxinterate"))
        self.gridLayout_5.addWidget(self.spinBox_maxinterate, 1, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_optimparameter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_5.addWidget(self.label_28, 1, 2, 1, 1)
        self.doubleSpinBox_crossoverp = QtGui.QDoubleSpinBox(self.groupBox_optimparameter)
        self.doubleSpinBox_crossoverp.setDecimals(2)
        self.doubleSpinBox_crossoverp.setMaximum(1.0)
        self.doubleSpinBox_crossoverp.setSingleStep(0.1)
        self.doubleSpinBox_crossoverp.setProperty("value", 1.0)
        self.doubleSpinBox_crossoverp.setObjectName(_fromUtf8("doubleSpinBox_crossoverp"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_crossoverp, 1, 3, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_optimparameter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 1, 4, 1, 1)
        self.doubleSpinBox_mutationp = QtGui.QDoubleSpinBox(self.groupBox_optimparameter)
        self.doubleSpinBox_mutationp.setMaximum(1.0)
        self.doubleSpinBox_mutationp.setSingleStep(0.01)
        self.doubleSpinBox_mutationp.setProperty("value", 0.02)
        self.doubleSpinBox_mutationp.setObjectName(_fromUtf8("doubleSpinBox_mutationp"))
        self.gridLayout_5.addWidget(self.doubleSpinBox_mutationp, 1, 5, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_optimparameter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 2, 0, 1, 1)
        self.spinBox_crosoverdist = QtGui.QSpinBox(self.groupBox_optimparameter)
        self.spinBox_crosoverdist.setMaximum(100)
        self.spinBox_crosoverdist.setProperty("value", 15)
        self.spinBox_crosoverdist.setObjectName(_fromUtf8("spinBox_crosoverdist"))
        self.gridLayout_5.addWidget(self.spinBox_crosoverdist, 2, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_optimparameter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_5.addWidget(self.label_32, 2, 2, 1, 1)
        self.spinBox_mutationdist = QtGui.QSpinBox(self.groupBox_optimparameter)
        self.spinBox_mutationdist.setMaximum(100)
        self.spinBox_mutationdist.setProperty("value", 20)
        self.spinBox_mutationdist.setObjectName(_fromUtf8("spinBox_mutationdist"))
        self.gridLayout_5.addWidget(self.spinBox_mutationdist, 2, 3, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox_optimparameter)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_5.addWidget(self.label_42, 2, 4, 1, 1)
        self.spinBox_archive = QtGui.QSpinBox(self.groupBox_optimparameter)
        self.spinBox_archive.setMaximum(500)
        self.spinBox_archive.setProperty("value", 50)
        self.spinBox_archive.setObjectName(_fromUtf8("spinBox_archive"))
        self.gridLayout_5.addWidget(self.spinBox_archive, 2, 5, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_optimparameter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_5.addWidget(self.label_44, 3, 0, 1, 1)
        self.spinBox_neighobersize = QtGui.QSpinBox(self.groupBox_optimparameter)
        self.spinBox_neighobersize.setMaximum(100)
        self.spinBox_neighobersize.setProperty("value", 10)
        self.spinBox_neighobersize.setObjectName(_fromUtf8("spinBox_neighobersize"))
        self.gridLayout_5.addWidget(self.spinBox_neighobersize, 3, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_optimparameter)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_5.addWidget(self.label_43, 3, 2, 1, 1)
        self.spinBox_gapsize = QtGui.QSpinBox(self.groupBox_optimparameter)
        self.spinBox_gapsize.setObjectName(_fromUtf8("spinBox_gapsize"))
        self.gridLayout_5.addWidget(self.spinBox_gapsize, 3, 3, 1, 1)
        self.pushButton_optim = QtGui.QPushButton(self.groupBox_optimparameter)
        self.pushButton_optim.setObjectName(_fromUtf8("pushButton_optim"))
        self.gridLayout_5.addWidget(self.pushButton_optim, 3, 4, 1, 1)
        self.pushButton_canceloptim = QtGui.QPushButton(self.groupBox_optimparameter)
        self.pushButton_canceloptim.setObjectName(_fromUtf8("pushButton_canceloptim"))
        self.gridLayout_5.addWidget(self.pushButton_canceloptim, 3, 5, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_optimparameter, 0, 0, 1, 1)
        self.groupBox_optimallocation = QtGui.QGroupBox(self.tab_4)
        self.groupBox_optimallocation.setObjectName(_fromUtf8("groupBox_optimallocation"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_optimallocation)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.matplotlibwidget_mapallocation = MatplotlibWidget(self.groupBox_optimallocation)
        self.matplotlibwidget_mapallocation.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibwidget_mapallocation.sizePolicy().hasHeightForWidth())
        self.matplotlibwidget_mapallocation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.matplotlibwidget_mapallocation.setFont(font)
        self.matplotlibwidget_mapallocation.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.matplotlibwidget_mapallocation.setStyleSheet(_fromUtf8("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.339795 rgba(255, 0, 0, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));"))
        self.matplotlibwidget_mapallocation.setObjectName(_fromUtf8("matplotlibwidget_mapallocation"))
        self.gridLayout_20.addWidget(self.matplotlibwidget_mapallocation, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_optimallocation, 0, 1, 2, 1)
        self.groupBox_optmiresult = QtGui.QGroupBox(self.tab_4)
        self.groupBox_optmiresult.setObjectName(_fromUtf8("groupBox_optmiresult"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_optmiresult)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.matplotlibwidget_curveoptim = MatplotlibWidget(self.groupBox_optmiresult)
        self.matplotlibwidget_curveoptim.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matplotlibwidget_curveoptim.sizePolicy().hasHeightForWidth())
        self.matplotlibwidget_curveoptim.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.matplotlibwidget_curveoptim.setFont(font)
        self.matplotlibwidget_curveoptim.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.matplotlibwidget_curveoptim.setStyleSheet(_fromUtf8("border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.339795 rgba(255, 0, 0, 255), stop:0.339799 rgba(255, 255, 255, 255), stop:0.662444 rgba(255, 255, 255, 255), stop:0.662469 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));"))
        self.matplotlibwidget_curveoptim.setObjectName(_fromUtf8("matplotlibwidget_curveoptim"))
        self.gridLayout_17.addWidget(self.matplotlibwidget_curveoptim, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.groupBox_optmiresult)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label = QtGui.QLabel(self.splitter)
        self.label.setObjectName(_fromUtf8("label"))
        self.comboBox_objective = QtGui.QComboBox(self.splitter)
        self.comboBox_objective.setObjectName(_fromUtf8("comboBox_objective"))
        self.pushButton_mapallocation = QtGui.QPushButton(self.splitter)
        self.pushButton_mapallocation.setObjectName(_fromUtf8("pushButton_mapallocation"))
        self.gridLayout_17.addWidget(self.splitter, 1, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_optmiresult, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_10.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "动态无功补偿装置多目标优化配置程序", None))
        self.pushButton_saveparameter.setText(_translate("MainWindow", "保存", None))
        self.pushButton_denyparameter.setText(_translate("MainWindow", "取消", None))
        self.groupBox_BPAprogram.setTitle(_translate("MainWindow", "BPA程序", None))
        self.toolButton_swntprogram.setText(_translate("MainWindow", "选择", None))
        self.label_pfprogram.setText(_translate("MainWindow", "潮流计算程序", None))
        self.label_resultfile.setText(_translate("MainWindow", "计算结果文件夹", None))
        self.toolButton_resultfile.setText(_translate("MainWindow", "选择", None))
        self.label_swntprogram.setText(_translate("MainWindow", "稳定批处理计算程序", None))
        self.toolButton_pfprogram.setText(_translate("MainWindow", "选择", None))
        self.groupBox_systemparameter.setTitle(_translate("MainWindow", "系统参数", None))
        self.label_loadrate.setText(_translate("MainWindow", "负荷增长率", None))
        self.label_dlrate.setText(_translate("MainWindow", "动态负荷比例", None))
        self.groupBox_systemdata.setTitle(_translate("MainWindow", "系统数据文件", None))
        self.label_pfdata.setText(_translate("MainWindow", "潮流数据文件", None))
        self.toolButton_pfdata.setText(_translate("MainWindow", "选择", None))
        self.label_bsedata.setText(_translate("MainWindow", "基态.BSE文件", None))
        self.toolButton__bsedata.setText(_translate("MainWindow", "选择", None))
        self.label_changedata.setText(_translate("MainWindow", "潮流修改文件", None))
        self.toolButton_changedata.setText(_translate("MainWindow", "选择", None))
        self.label_swntdata.setText(_translate("MainWindow", "稳定数据文件", None))
        self.toolButton_swntdata.setText(_translate("MainWindow", "选择", None))
        self.label_falutratedata.setText(_translate("MainWindow", "故障率数据文件", None))
        self.toolButton_faultratedata.setText(_translate("MainWindow", "选择", None))
        self.label_mapdata.setText(_translate("MainWindow", "地理位置文件", None))
        self.toolButton_mapdata.setText(_translate("MainWindow", "选择", None))
        self.groupBox_DVparameter.setTitle(_translate("MainWindow", "动态无功补偿装置参数", None))
        self.label_dvtype.setText(_translate("MainWindow", "补偿装置类型", None))
        self.label_maxrate.setText(_translate("MainWindow", "最大容量", None))
        self.label_mingap.setText(_translate("MainWindow", "最小容量间隔", None))
        self.label_fixedcost.setText(_translate("MainWindow", "固定安装费用", None))
        self.label_17.setText(_translate("MainWindow", "购买费用", None))
        self.checkBox_statcom.setText(_translate("MainWindow", "STATCOM", None))
        self.label_22.setText(_translate("MainWindow", "MVar", None))
        self.label_25.setText(_translate("MainWindow", "MVar", None))
        self.label_35.setText(_translate("MainWindow", "万元", None))
        self.label_37.setText(_translate("MainWindow", "万元/MVar", None))
        self.checkBox_svc.setText(_translate("MainWindow", "SVC", None))
        self.label_23.setText(_translate("MainWindow", "MVar", None))
        self.label_24.setText(_translate("MainWindow", "MVar", None))
        self.label_36.setText(_translate("MainWindow", "万元", None))
        self.label_38.setText(_translate("MainWindow", "万元/MVar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "基本参数设置", None))
        self.pushButton_faultanalyse.setText(_translate("MainWindow", "故障扫描分析", None))
        self.groupBox_chooseignorefault.setTitle(_translate("MainWindow", "选择忽略故障", None))
        self.pushButton_addfault.setText(_translate("MainWindow", "添加", None))
        self.pushButton_canclefault.setText(_translate("MainWindow", "删除", None))
        self.groupBox_mapkeyfault.setTitle(_translate("MainWindow", "关键扰动位置图", None))
        self.pushButton_kmeansfault.setText(_translate("MainWindow", "K-means聚类分析", None))
        self.pushButton_mapkeyfault.setText(_translate("MainWindow", "关键扰动位置示意", None))
        self.groupBox_barkeyfault.setTitle(_translate("MainWindow", "关键扰动分析结果", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "关键故障分析", None))
        self.pushButton_senscompute.setText(_translate("MainWindow", "灵敏度计算", None))
        self.pushButton_senskmeans.setText(_translate("MainWindow", "K-means聚类分析", None))
        self.pushButton_mapsens.setText(_translate("MainWindow", "灵敏母线位置示意", None))
        self.groupBox_ignorebus.setTitle(_translate("MainWindow", "选择忽略母线", None))
        self.pushButton_addbus.setText(_translate("MainWindow", "添加", None))
        self.pushButton_canclebus.setText(_translate("MainWindow", "删除", None))
        self.groupBox_mapsens.setTitle(_translate("MainWindow", "灵敏母线位置图", None))
        self.groupBox_sensbus.setTitle(_translate("MainWindow", "灵敏母线分析结果", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "灵敏母线分析", None))
        self.groupBox_optimparameter.setTitle(_translate("MainWindow", "优化算法参数", None))
        self.label_typealgorithm.setText(_translate("MainWindow", "优化算法类型", None))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "NSGAII", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "NSGAIII", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "MOEA/D", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "SPEA2", None))
        self.label_33.setText(_translate("MainWindow", "随机数种子", None))
        self.label_27.setText(_translate("MainWindow", "种群数量", None))
        self.label_maxinterate.setText(_translate("MainWindow", "最大迭代次数", None))
        self.label_28.setText(_translate("MainWindow", "交叉概率", None))
        self.label_29.setText(_translate("MainWindow", "变异概率", None))
        self.label_31.setText(_translate("MainWindow", "交叉分布因子", None))
        self.label_32.setText(_translate("MainWindow", "变异分布因子", None))
        self.label_42.setText(_translate("MainWindow", "外部档案大小", None))
        self.label_44.setText(_translate("MainWindow", "邻域数量", None))
        self.label_43.setText(_translate("MainWindow", "间隔大小", None))
        self.pushButton_optim.setText(_translate("MainWindow", "开始", None))
        self.pushButton_canceloptim.setText(_translate("MainWindow", "取消", None))
        self.groupBox_optimallocation.setTitle(_translate("MainWindow", "最优配置方案示意图", None))
        self.groupBox_optmiresult.setTitle(_translate("MainWindow", "优化结果", None))
        self.label.setText(_translate("MainWindow", "目标函数值", None))
        self.pushButton_mapallocation.setText(_translate("MainWindow", "显示配置方案", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "优化计算", None))

from matplotlibwidget import MatplotlibWidget
